# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
weight = 2
name = "L'association"

[[main]]
parent = "L'association"
name = "Notre engagement"
url = "/association-airsoft-lyon"
weight = 1

[[main]]
parent = "L'association"
name = "Notre scénario"
url = "/scenario-airsoft"
weight = 2

[[main]]
parent = "L'association"
name = "Nos terrains"
url = "/terrains-airsoft-lyon"
weight = 3

[[main]]
parent = "L'association"
name = "Anciens terrains"
url = "/anciens-terrains-airsoft"
weight = 4

[[main]]
weight = 3
name = "Nos parties"

[[main]]
parent = "Nos parties"
name = "Inscription"
url = "/jouer-airsoft-lyon"
weight = 1

[[main]]
parent = "Nos parties"
name = "Une journée type"
url = "/journee-airsoft-lyon"
weight = 2

[[main]]
parent = "Nos parties"
name = "Nos règles de jeu"
url = "/regles-airsoft"
weight = 3

[[main]]
name = "Boutique"
url = "/boutique-airsoft"
weight = 4

[[main]]
name = "Autres assos"
url = "/autres-associations-airsoft"
weight = 5

# [[main]]
# weight = 6
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"

# [[main]]
# parent = "Pages"
# name = "About"
# url = "/about"

# [[main]]
# parent = "Pages"
# name = "Elements"
# url = "/elements"


# footer menu
[[footer]]
name = "L'association"
url = "/association-airsoft-lyon"
weight = 1

[[footer]]
name = "La FFA"
url = "/https://ffairsoft.org/"
weight = 2

[[footer]]
name = "Nos parties"
url = "/jouer-airsoft-lyon"
weight = 3
